name: Python Package using Conda

on: [push]

jobs:
  build-for-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
          activate-environment: rcwa-torch
          environment-file: environment.yml
    - name: check essential package
      run: |
        conda activate rcwa-torch
        conda info
        conda list
    # - name: Install package
    #   run: |
    #     conda install pip
    #     pip install -e .  # install package in editable mode
    # - name: Test with pytest
    #   run: |
    #     conda install pytest
    #     python -m pytest testing/
